pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url 'http://maven.tapsell.ir/repository/maven-releases/'; allowInsecureProtocol = true }
        maven { url 'https://repo.tapsell.ir/repository/maven-releases/' }
    }
}
rootProject.name = "AmarMasrafInternet"
include ':app'
