pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        mavenCentral()
        maven { url "https://maven.tapsell.ir/repository/maven-releases/" }
        maven { url "https://jitpack.io" }
    }
}
rootProject.name = "AmarMasrafInternet"
include ':app'
